import { Text } from "@/components";
import { useHaptic } from "@/hooks/useHaptics";
import { routesNames } from "@/router/config/routesNames";
import { blendWithWhite } from "@/utils/colorGenerator";
import { useNavigation } from "@react-navigation/native";
import { useMemo, useRef, useState } from "react";
import { FlatList, TouchableOpacity, View } from "react-native";
export default function LastGrades({}) {
    const [lastGrades, setLastGrades] = useState([
        {
            libelle: "CO Invest on Mars or save Earth ?",
            notSignificant: false,
            date: "2026-06-08",
            isExam: false,
            homeworkType: "Interrogation écrite",
            disciplineName: "Ecrit",
            codes: {
                period: "A002",
                discipline: "AGL2",
            },
            data: {
                coef: 1,
                classAverage: 14.11,
                outOf: 20,
                classMax: 20,
                classMin: 7.5,
                grade: 11,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(275.016, 70%, 55%)",
            disciplineData: {
                code: "AGL2",
                libelle: "ANGLAIS LV2",
                color: "hsl(275.016, 70%, 55%)",
                averageDatas: {
                    classAverage: 17.01,
                    minAverage: 13.88,
                    maxAverage: 19.88,
                    userAverage: 14.81,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 24,
                rank: 17,
                teachers: ["Mme GAL J."],
                grades: [
                    {
                        libelle: "audioguide about Banksy's graffitti",
                        notSignificant: false,
                        date: "2026-02-17",
                        isExam: false,
                        homeworkType: "Présentation orale",
                        disciplineName: "Oral",
                        codes: {
                            period: "A002",
                            discipline: "AGL2",
                        },
                        data: {
                            coef: 1,
                            classAverage: 9.46,
                            outOf: 10,
                            classMax: 10,
                            classMin: 7,
                            grade: 8,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [],
                    },
                    {
                        libelle: "create the truest fake news",
                        notSignificant: false,
                        date: "2026-04-22",
                        isExam: false,
                        homeworkType: "Présentation orale",
                        disciplineName: "Oral",
                        codes: {
                            period: "A002",
                            discipline: "AGL2",
                        },
                        data: {
                            coef: 1,
                            classAverage: 19,
                            outOf: 20,
                            classMax: 20,
                            classMin: 15,
                            grade: 15,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_discipline_average"],
                    },
                    {
                        libelle:
                            "Can art make you happier / challenge the power of the establishment ?",
                        notSignificant: false,
                        date: "2026-05-02",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "Oral",
                        codes: {
                            period: "A002",
                            discipline: "AGL2",
                        },
                        data: {
                            coef: 1,
                            classAverage: 15.75,
                            outOf: 20,
                            classMax: 19.5,
                            classMin: 6.5,
                            grade: 17.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "CO Invest on Mars or save Earth ?",
                        notSignificant: false,
                        date: "2026-06-08",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "Ecrit",
                        codes: {
                            period: "A002",
                            discipline: "AGL2",
                        },
                        data: {
                            coef: 1,
                            classAverage: 14.11,
                            outOf: 20,
                            classMax: 20,
                            classMin: 7.5,
                            grade: 11,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                ],
                streakCount: 0,
            },
        },
        {
            libelle: "Projet",
            notSignificant: false,
            date: "2026-06-04",
            isExam: false,
            homeworkType: "Travail de groupe",
            disciplineName: "SCIENCES INGENIEUR",
            codes: {
                period: "A002",
                discipline: "SC-IG",
            },
            data: {
                coef: 0.5,
                classAverage: 18,
                outOf: 20,
                classMax: 18,
                classMin: 18,
                grade: 18,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(20.064000000000078, 70%, 55%)",
            disciplineData: {
                code: "SC-IG",
                libelle: "SCIENCES INGENIEUR",
                color: "hsl(20.064000000000078, 70%, 55%)",
                averageDatas: {
                    classAverage: 15.52,
                    minAverage: 10.9,
                    maxAverage: 17.85,
                    userAverage: 16.73,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 32,
                rank: 17,
                teachers: ["M. BIREM K.", "M. MALOU Z."],
                grades: [
                    {
                        libelle: "Python",
                        notSignificant: false,
                        date: "2026-04-16",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 16.42,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9.75,
                            grade: 19.75,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "Réseau",
                        notSignificant: false,
                        date: "2026-05-07",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 15.53,
                            outOf: 20,
                            classMax: 20,
                            classMin: 8,
                            grade: 17,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "DST",
                        notSignificant: false,
                        date: "2026-05-22",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 13.9,
                            outOf: 20,
                            classMax: 18.5,
                            classMin: 10.5,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                    {
                        libelle: "Projet",
                        notSignificant: false,
                        date: "2026-06-04",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 18,
                            outOf: 20,
                            classMax: 18,
                            classMin: 18,
                            grade: 18,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "best_grade",
                            "upper_than_discipline_average",
                        ],
                    },
                ],
                streakCount: 1,
            },
        },
        {
            libelle: "kwyk",
            notSignificant: false,
            date: "2026-06-03",
            isExam: false,
            homeworkType: "Devoir maison",
            disciplineName: "MATHEMATIQUES",
            codes: {
                period: "A002",
                discipline: "MATHS",
            },
            data: {
                coef: 0.1,
                classAverage: 18.15,
                outOf: 20,
                classMax: 20,
                classMin: 15,
                grade: 18,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(105.048, 70%, 55%)",
            disciplineData: {
                code: "MATHS",
                libelle: "MATHEMATIQUES",
                color: "hsl(105.048, 70%, 55%)",
                averageDatas: {
                    classAverage: 14.08,
                    minAverage: 8.52,
                    maxAverage: 18.17,
                    userAverage: 15.38,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 28,
                rank: 20,
                teachers: ["Mme GARNIER E."],
                grades: [
                    {
                        libelle: "Suites",
                        notSignificant: false,
                        date: "2026-02-16",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 15.1,
                            outOf: 20,
                            classMax: 19.5,
                            classMin: 11.5,
                            grade: 15.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Proba-Suites-Dériavation globale",
                        notSignificant: false,
                        date: "2026-03-26",
                        isExam: false,
                        homeworkType: "Examen Blanc",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 12.46,
                            outOf: 20,
                            classMax: 18,
                            classMin: 7,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Trigo_Exponentielle",
                        notSignificant: false,
                        date: "2026-05-23",
                        isExam: false,
                        homeworkType: "Examen Blanc",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 2,
                            classAverage: 13.91,
                            outOf: 20,
                            classMax: 19,
                            classMin: 6,
                            grade: 16.5,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "kwyk",
                        notSignificant: false,
                        date: "2026-06-03",
                        isExam: false,
                        homeworkType: "Devoir maison",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 0.1,
                            classAverage: 18.15,
                            outOf: 20,
                            classMax: 20,
                            classMin: 15,
                            grade: 18,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: ["up_the_streak", "upper_than_discipline_average"],
                    },
                ],
                streakCount: 2,
            },
        },
        {
            libelle: "Escalade",
            notSignificant: false,
            date: "2026-06-01",
            isExam: false,
            homeworkType: "Autre",
            disciplineName: "ED.PHYSIQUE & SPORT.",
            codes: {
                period: "A002",
                discipline: "EPS",
            },
            data: {
                coef: 1,
                classAverage: 17.67,
                outOf: 20,
                classMax: 20,
                classMin: 14,
                grade: 20,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(157.57200000000012, 70%, 55%)",
            disciplineData: {
                code: "EPS",
                libelle: "ED.PHYSIQUE & SPORT.",
                color: "hsl(157.57200000000012, 70%, 55%)",
                averageDatas: {
                    classAverage: 16.25,
                    minAverage: 10.5,
                    maxAverage: 19.75,
                    userAverage: 18.63,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 37,
                rank: 21,
                teachers: ["M. LAHITTE N."],
                grades: [
                    {
                        libelle: "Demi-Fond",
                        notSignificant: false,
                        date: "2026-03-30",
                        isExam: false,
                        homeworkType: "Autre",
                        disciplineName: "ED.PHYSIQUE & SPORT.",
                        codes: {
                            period: "A002",
                            discipline: "EPS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 15.35,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9.5,
                            grade: 17.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: ["up_the_streak", "upper_than_class_average"],
                    },
                    {
                        libelle: "Escalade",
                        notSignificant: false,
                        date: "2026-06-01",
                        isExam: false,
                        homeworkType: "Autre",
                        disciplineName: "ED.PHYSIQUE & SPORT.",
                        codes: {
                            period: "A002",
                            discipline: "EPS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 17.67,
                            outOf: 20,
                            classMax: 20,
                            classMin: 14,
                            grade: 20,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "max_grade",
                            "best_grade",
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                ],
                streakCount: 2,
            },
        },
        {
            libelle: "Évaluation n°5 chapitres 14 et 15",
            notSignificant: false,
            date: "2026-05-29",
            isExam: false,
            homeworkType: "Interrogation écrite",
            disciplineName: "PHYSIQUE-CHIMIE",
            codes: {
                period: "A002",
                discipline: "PH-CH",
            },
            data: {
                coef: 1,
                classAverage: 16.75,
                outOf: 20,
                classMax: 20,
                classMin: 12,
                grade: 17,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(242.55600000000004, 70%, 55%)",
            disciplineData: {
                code: "PH-CH",
                libelle: "PHYSIQUE-CHIMIE",
                color: "hsl(242.55600000000004, 70%, 55%)",
                averageDatas: {
                    classAverage: 14.34,
                    minAverage: 11.81,
                    maxAverage: 17.1,
                    userAverage: 16.31,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 18,
                rank: 11,
                teachers: ["M. GAUTIER F."],
                grades: [
                    {
                        libelle: "TP n°15 Solubilité",
                        notSignificant: false,
                        date: "2026-02-13",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "PHYSIQUE-CHIMIE",
                        codes: {
                            period: "A002",
                            discipline: "PH-CH",
                        },
                        data: {
                            coef: 0.25,
                            classAverage: 3.56,
                            outOf: 5,
                            classMax: 4.5,
                            classMin: 3,
                            grade: 4,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Évaluation n°3 chapitres 5 et 13",
                        notSignificant: false,
                        date: "2026-02-16",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "PHYSIQUE-CHIMIE",
                        codes: {
                            period: "A002",
                            discipline: "PH-CH",
                        },
                        data: {
                            coef: 1,
                            classAverage: 15,
                            outOf: 20,
                            classMax: 17.5,
                            classMin: 12.25,
                            grade: 16.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "DST n°4",
                        notSignificant: false,
                        date: "2026-04-02",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "PHYSIQUE-CHIMIE",
                        codes: {
                            period: "A002",
                            discipline: "PH-CH",
                        },
                        data: {
                            coef: 2,
                            classAverage: null,
                            outOf: 20,
                            classMax: null,
                            classMin: null,
                            grade: null,
                        },
                        skills: [],
                        onlySkills: false,
                        badges: [],
                    },
                    {
                        libelle: "Évaluation n°4 chapitres 7 et 18",
                        notSignificant: false,
                        date: "2026-05-04",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "PHYSIQUE-CHIMIE",
                        codes: {
                            period: "A002",
                            discipline: "PH-CH",
                        },
                        data: {
                            coef: 1,
                            classAverage: 14.5,
                            outOf: 20,
                            classMax: 18.25,
                            classMin: 9,
                            grade: 15.75,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Évaluation n°5 chapitres 14 et 15",
                        notSignificant: false,
                        date: "2026-05-29",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "PHYSIQUE-CHIMIE",
                        codes: {
                            period: "A002",
                            discipline: "PH-CH",
                        },
                        data: {
                            coef: 1,
                            classAverage: 16.75,
                            outOf: 20,
                            classMax: 20,
                            classMin: 12,
                            grade: 17,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                ],
                streakCount: 1,
            },
        },
        {
            libelle: "Trigo_Exponentielle",
            notSignificant: false,
            date: "2026-05-23",
            isExam: false,
            homeworkType: "Examen Blanc",
            disciplineName: "MATHEMATIQUES",
            codes: {
                period: "A002",
                discipline: "MATHS",
            },
            data: {
                coef: 2,
                classAverage: 13.91,
                outOf: 20,
                classMax: 19,
                classMin: 6,
                grade: 16.5,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(105.048, 70%, 55%)",
            disciplineData: {
                code: "MATHS",
                libelle: "MATHEMATIQUES",
                color: "hsl(105.048, 70%, 55%)",
                averageDatas: {
                    classAverage: 14.08,
                    minAverage: 8.52,
                    maxAverage: 18.17,
                    userAverage: 15.38,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 28,
                rank: 20,
                teachers: ["Mme GARNIER E."],
                grades: [
                    {
                        libelle: "Suites",
                        notSignificant: false,
                        date: "2026-02-16",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 15.1,
                            outOf: 20,
                            classMax: 19.5,
                            classMin: 11.5,
                            grade: 15.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Proba-Suites-Dériavation globale",
                        notSignificant: false,
                        date: "2026-03-26",
                        isExam: false,
                        homeworkType: "Examen Blanc",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 1,
                            classAverage: 12.46,
                            outOf: 20,
                            classMax: 18,
                            classMin: 7,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Trigo_Exponentielle",
                        notSignificant: false,
                        date: "2026-05-23",
                        isExam: false,
                        homeworkType: "Examen Blanc",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 2,
                            classAverage: 13.91,
                            outOf: 20,
                            classMax: 19,
                            classMin: 6,
                            grade: 16.5,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "kwyk",
                        notSignificant: false,
                        date: "2026-06-03",
                        isExam: false,
                        homeworkType: "Devoir maison",
                        disciplineName: "MATHEMATIQUES",
                        codes: {
                            period: "A002",
                            discipline: "MATHS",
                        },
                        data: {
                            coef: 0.1,
                            classAverage: 18.15,
                            outOf: 20,
                            classMax: 20,
                            classMin: 15,
                            grade: 18,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: ["up_the_streak", "upper_than_discipline_average"],
                    },
                ],
                streakCount: 2,
            },
        },
        {
            libelle: "DST",
            notSignificant: false,
            date: "2026-05-22",
            isExam: false,
            homeworkType: "Devoir sur table",
            disciplineName: "SCIENCES INGENIEUR",
            codes: {
                period: "A002",
                discipline: "SC-IG",
            },
            data: {
                coef: 1.5,
                classAverage: 13.9,
                outOf: 20,
                classMax: 18.5,
                classMin: 10.5,
                grade: 13,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(20.064000000000078, 70%, 55%)",
            disciplineData: {
                code: "SC-IG",
                libelle: "SCIENCES INGENIEUR",
                color: "hsl(20.064000000000078, 70%, 55%)",
                averageDatas: {
                    classAverage: 15.52,
                    minAverage: 10.9,
                    maxAverage: 17.85,
                    userAverage: 16.73,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 32,
                rank: 17,
                teachers: ["M. BIREM K.", "M. MALOU Z."],
                grades: [
                    {
                        libelle: "Python",
                        notSignificant: false,
                        date: "2026-04-16",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 16.42,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9.75,
                            grade: 19.75,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "Réseau",
                        notSignificant: false,
                        date: "2026-05-07",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 15.53,
                            outOf: 20,
                            classMax: 20,
                            classMin: 8,
                            grade: 17,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "DST",
                        notSignificant: false,
                        date: "2026-05-22",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 13.9,
                            outOf: 20,
                            classMax: 18.5,
                            classMin: 10.5,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                    {
                        libelle: "Projet",
                        notSignificant: false,
                        date: "2026-06-04",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 18,
                            outOf: 20,
                            classMax: 18,
                            classMin: 18,
                            grade: 18,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "best_grade",
                            "upper_than_discipline_average",
                        ],
                    },
                ],
                streakCount: 1,
            },
        },
        {
            libelle: "Oral présentation âge de la Terre",
            notSignificant: false,
            date: "2026-05-13",
            isExam: false,
            homeworkType: "Présentation orale",
            disciplineName: "ENSEIGN.SCIENTIFIQUE",
            codes: {
                period: "A002",
                discipline: "G-SCI",
            },
            data: {
                coef: 1,
                classAverage: 17.42,
                outOf: 20,
                classMax: 20,
                classMin: 15,
                grade: 18.5,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(327.5400000000001, 70%, 55%)",
            disciplineData: {
                code: "G-SCI",
                libelle: "ENSEIGN.SCIENTIFIQUE",
                color: "hsl(327.5400000000001, 70%, 55%)",
                averageDatas: {
                    classAverage: 16.28,
                    minAverage: 10.71,
                    maxAverage: 18.75,
                    userAverage: 18.62,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 33,
                rank: 16,
                teachers: ["M. BURGESS G.", "Mme ARQUETOUX C."],
                grades: [
                    {
                        libelle: "DST n° 2 partie SVT",
                        notSignificant: false,
                        date: "2026-03-26",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 2,
                            classAverage: 15.66,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9,
                            grade: 19,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "TP Wien",
                        notSignificant: false,
                        date: "2026-04-01",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 14.67,
                            outOf: 20,
                            classMax: 17.5,
                            classMin: 10.5,
                            grade: 16.25,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Interro chap 7",
                        notSignificant: false,
                        date: "2026-04-08",
                        isExam: false,
                        homeworkType: "Interrogation écrite",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 1,
                            classAverage: 17.67,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9,
                            grade: 20,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "max_grade",
                            "best_grade",
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "TP Delambre et Méchain",
                        notSignificant: false,
                        date: "2026-04-15",
                        isExam: false,
                        homeworkType: "Autre",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 7.13,
                            outOf: 10,
                            classMax: 9.5,
                            classMin: 5,
                            grade: 8,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                    {
                        libelle: "Contrôle Chapitre 4",
                        notSignificant: false,
                        date: "2026-05-06",
                        isExam: false,
                        homeworkType: "Évaluation écrite",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 1,
                            classAverage: 16.04,
                            outOf: 20,
                            classMax: 20,
                            classMin: 8.24,
                            grade: 19.12,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "Oral présentation âge de la Terre",
                        notSignificant: false,
                        date: "2026-05-13",
                        isExam: false,
                        homeworkType: "Présentation orale",
                        disciplineName: "ENSEIGN.SCIENTIFIQUE",
                        codes: {
                            period: "A002",
                            discipline: "G-SCI",
                        },
                        data: {
                            coef: 1,
                            classAverage: 17.42,
                            outOf: 20,
                            classMax: 20,
                            classMin: 15,
                            grade: 18.5,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: ["upper_than_class_average"],
                    },
                ],
                streakCount: 0,
            },
        },
        {
            libelle: "oral blanc",
            notSignificant: false,
            date: "2026-05-13",
            isExam: false,
            homeworkType: "Interrogation Orale",
            disciplineName: "FRANCAIS",
            codes: {
                period: "A002",
                discipline: "FRANC",
            },
            data: {
                coef: 1,
                classAverage: 13.61,
                outOf: 20,
                classMax: 17.5,
                classMin: 9,
                grade: 11,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(0, 70%, 55%)",
            disciplineData: {
                code: "FRANC",
                libelle: "FRANCAIS",
                color: "hsl(0, 70%, 55%)",
                averageDatas: {
                    classAverage: 13.55,
                    minAverage: 9.46,
                    maxAverage: 17.62,
                    userAverage: 14.54,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 33,
                rank: 30,
                teachers: ["Mme BEUTTER C."],
                grades: [
                    {
                        libelle: "Ecrit d'appropriation Colette",
                        notSignificant: false,
                        date: "2026-02-02",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "FRANCAIS",
                        codes: {
                            period: "A002",
                            discipline: "FRANC",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 17.97,
                            outOf: 20,
                            classMax: 20,
                            classMin: 17,
                            grade: 19,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle:
                            "Oral blanc - Lecture linéaire + question grammaire",
                        notSignificant: false,
                        date: "2026-02-06",
                        isExam: false,
                        homeworkType: "Interrogation Orale",
                        disciplineName: "FRANCAIS",
                        codes: {
                            period: "A002",
                            discipline: "FRANC",
                        },
                        data: {
                            coef: 1,
                            classAverage: 14.28,
                            outOf: 20,
                            classMax: 19,
                            classMin: 8.5,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                    {
                        libelle: "Dissertation type bac - Fontenelle",
                        notSignificant: false,
                        date: "2026-03-17",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "FRANCAIS",
                        codes: {
                            period: "A002",
                            discipline: "FRANC",
                        },
                        data: {
                            coef: 3,
                            classAverage: 11.6,
                            outOf: 20,
                            classMax: 17,
                            classMin: 7,
                            grade: 15,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "Dissertation ou commentaire type bac",
                        notSignificant: false,
                        date: "2026-05-07",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "FRANCAIS",
                        codes: {
                            period: "A002",
                            discipline: "FRANC",
                        },
                        data: {
                            coef: 1,
                            classAverage: 16.23,
                            outOf: 20,
                            classMax: 19,
                            classMin: 10,
                            grade: 16,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: ["upper_than_discipline_average"],
                    },
                    {
                        libelle: "oral blanc",
                        notSignificant: false,
                        date: "2026-05-13",
                        isExam: false,
                        homeworkType: "Interrogation Orale",
                        disciplineName: "FRANCAIS",
                        codes: {
                            period: "A002",
                            discipline: "FRANC",
                        },
                        data: {
                            coef: 1,
                            classAverage: 13.61,
                            outOf: 20,
                            classMax: 17.5,
                            classMin: 9,
                            grade: 11,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                ],
                streakCount: 0,
            },
        },
        {
            libelle: "Réseau",
            notSignificant: false,
            date: "2026-05-07",
            isExam: false,
            homeworkType: "Devoir sur table",
            disciplineName: "SCIENCES INGENIEUR",
            codes: {
                period: "A002",
                discipline: "SC-IG",
            },
            data: {
                coef: 1.5,
                classAverage: 15.53,
                outOf: 20,
                classMax: 20,
                classMin: 8,
                grade: 17,
            },
            skills: [],
            onlySkills: false,
            badges: [],
            disciplineColor: "hsl(20.064000000000078, 70%, 55%)",
            disciplineData: {
                code: "SC-IG",
                libelle: "SCIENCES INGENIEUR",
                color: "hsl(20.064000000000078, 70%, 55%)",
                averageDatas: {
                    classAverage: 15.52,
                    minAverage: 10.9,
                    maxAverage: 17.85,
                    userAverage: 16.73,
                },
                coef: 1,
                isDisciplineGroup: false,
                workforce: 32,
                rank: 17,
                teachers: ["M. BIREM K.", "M. MALOU Z."],
                grades: [
                    {
                        libelle: "Python",
                        notSignificant: false,
                        date: "2026-04-16",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 16.42,
                            outOf: 20,
                            classMax: 20,
                            classMin: 9.75,
                            grade: 19.75,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "previous up",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "Réseau",
                        notSignificant: false,
                        date: "2026-05-07",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 15.53,
                            outOf: 20,
                            classMax: 20,
                            classMin: 8,
                            grade: 17,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [
                            "upper_than_class_average",
                            "upper_than_discipline_average",
                        ],
                    },
                    {
                        libelle: "DST",
                        notSignificant: false,
                        date: "2026-05-22",
                        isExam: false,
                        homeworkType: "Devoir sur table",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 1.5,
                            classAverage: 13.9,
                            outOf: 20,
                            classMax: 18.5,
                            classMin: 10.5,
                            grade: 13,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "nothing",
                        badges: [],
                    },
                    {
                        libelle: "Projet",
                        notSignificant: false,
                        date: "2026-06-04",
                        isExam: false,
                        homeworkType: "Travail de groupe",
                        disciplineName: "SCIENCES INGENIEUR",
                        codes: {
                            period: "A002",
                            discipline: "SC-IG",
                        },
                        data: {
                            coef: 0.5,
                            classAverage: 18,
                            outOf: 20,
                            classMax: 18,
                            classMin: 18,
                            grade: 18,
                        },
                        skills: [],
                        onlySkills: false,
                        actionOnStreak: "up",
                        badges: [
                            "up_the_streak",
                            "best_grade",
                            "upper_than_discipline_average",
                        ],
                    },
                ],
                streakCount: 1,
            },
        },
    ]);

    const navigation = useNavigation();
    const hapticFeedback = useHaptic("heavy");

    const onViewableItemsChanged = useRef(({ viewableItems }) => {
        if (viewableItems.length > 0) {
            hapticFeedback(); // the haptics doesn't work, idk why, maybe regenerate dev client ?
        }
    }).current;

    const viewabilityConfig = useRef({
        itemVisiblePercentThreshold: 50,
    }).current;

    return (
        <View style={{ height: 100 }}>
            <FlatList
                onViewableItemsChanged={onViewableItemsChanged}
                viewabilityConfig={viewabilityConfig}
                data={lastGrades}
                horizontal
                showsHorizontalScrollIndicator={false}
                keyExtractor={(item) => item.libelle}
                contentContainerStyle={{ gap: 10 }}
                renderItem={({ item }) => (
                    <TouchableOpacity
                        onPress={() => {
                            console.log(item);
                            navigation.navigate(routesNames.client.grades.group, {
                                screen: routesNames.client.grades.details,
                                params: {
                                    gradesData: item,
                                    disciplineData: item.disciplineData,
                                },
                            });
                        }}
                    >
                        <GradeCard
                            disciplineColor={item.disciplineColor}
                            disciplineData={item.disciplineData}
                            data={item.data}
                        />
                    </TouchableOpacity>
                )}
            />
        </View>
    );
}
const GradeCard = ({ disciplineColor, disciplineData: { libelle }, data }) => {
    const lightColor = useMemo(
        () => blendWithWhite(disciplineColor, 0.35),
        [disciplineColor]
    );
    return (
        <View
            style={{
                backgroundColor: "hsla(235, 28%, 15%, 1)",
                borderRadius: 16,
                width: 150,
                paddingHorizontal: 20,
                paddingVertical: 19,
                justifyContent: "space-between",
            }}
        >
            <Text align="left" oneLine style={{ color: disciplineColor }}>
                {libelle.toUpperCase()}
            </Text>

            <View
                style={{
                    flexDirection: "row",
                    alignItems: "flex-start",
                    justifyContent: "center",
                }}
            >
                <Text preset="h3" color={lightColor}>
                    {data.grade.toFixed(2)}
                    <Text preset="label2" color="hsla(1, 0%, 100%, .55)">
                        /{data.outOf}
                    </Text>
                </Text>
                <Text
                    preset="label3"
                    color="hsla(1, 0%, 100%, .55)"
                    style={{ marginLeft: 2 }}
                >
                    ({data.coef})
                </Text>
            </View>
        </View>
    );
};

